--- #YAML:1.0
name:                Dir-Self
version:             0.10
abstract:            a __DIR__ constant for the directory your source file is in
license:             ~
author:              
    - Lukas Mai <l.mai @web.de>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    File::Spec:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
